global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'chengeto-health'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []
rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'chengeto-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'
