name: CI

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  backend:
    name: Backend CI
    uses: ./.github/workflows/_backend-ci.yml

  frontend:
    name: Frontend CI
    uses: ./.github/workflows/_frontend-ci.yml
